# OBJ_SAMPLE_X_HIGH_LOW: [0.435, 0.475]
# OBJ_SAMPLE_Y_HIGH_LOW: [-0.05, 0.15]
OBJ_SAMPLE_X_HIGH_LOW: [0.225, 0.325]
OBJ_SAMPLE_Y_HIGH_LOW: [-0.05, 0.15]

MESH_SCALE_HIGH: 0.35
MESH_SCALE_LOW: 0.2

PREPLACE_HORIZONTAL_OFFSET_TF: [0, 0.2, 0, 0, 0, 0, 1]
PREPLACE_OFFSET_TF: [0, 0.0, 0.05, 0, 0, 0, 1]

DEMOS:
  PLACEMENT_SURFACE: 'shelf'
