OBJ_SAMPLE_X_HIGH_LOW: [0.3, 0.35]
OBJ_SAMPLE_Y_HIGH_LOW: [-0.25, 0.25]
OBJ_SAMPLE_Z_HIGH_LOW: [1.1, 1.3]

MESH_SCALE_DEFAULT: 0.2
MESH_SCALE_HIGH: 0.35
MESH_SCALE_LOW: 0.175

CAMERA:
  FOCUS_PT: [0.5, 0.0, 0.0]